### ISSUE TITLE
In server configuration

### ISSUE THREAD

**Issue by FSFan** [kwifrog/MiniCoal#1]
Does not seem to work on a server.  Wont even load even though no error is given.  Version for 1.10.2

**Comment by kwifrog** [comment]
Do you also have it installed on your client? That's the only thing I can think of that would cause it to "not load"

It's been on a heavily used server working just fine.

**Comment by FSFan** [comment]
Thanx for the quick get-back.  I have v1.1.0 installed on both the client and the server.  Single player works fine, multiplayer doesnt work.  Could it have to do with the fact that it's on a local server?

**Comment by kwifrog** [comment]
I'm not sure what would be the difference code-wise, but I'll look into it.

**Comment by FSFan** [comment]
I know programming as well although Java is not my language of choice.  I'd be glad to help look it over if you want.

**Comment by gigabit101** [comment]
There is no issue with the config code it is the same code I use in all my mods so... your doing it wrong??

**Comment by kwifrog** [comment]
Yea, make sure the config settings are the same. It's something on your end, everything is fine.

**Comment by FSFan** [comment]
You can close this.  I figured out what I was doing.  Thanx.
