### ISSUE TITLE
Minicoal prevents me from turning coal blocks back into coal, or smelting wood into charcoal.

### ISSUE THREAD

**Issue by Angular-Angel** [kwifrog/MiniCoal#7]
It's because you put your 'minicoal and minicharcoal back into regular coal and charcoal' recipes in the minecraft directory, instead of your own mods directory, and as such they override other recipes with the same name - specifically, the vanilla minecraft recipes. Move those recipes into the mods own recipe folder, and that should fix the bug. Also, while you're at it, turn them into shapeless recipes, needing to fit the exact pattern is silly and annoying.

Love the mod though! Keep up the good work. XD

**Comment by kwifrog** [comment]
The recipe placement is fine, I just didn't give it a unique name whoops, so I'll work on sorting that out. And yea, I'll make them shapeless :^) Thanks for the report!

**Comment by kwifrog** [comment]
Fixed in 98f7fcb

File has been uploaded to Curse and approved :)
